---
- name: Check if installed
  shell: /usr/bin/test `nginx -v 2>&1 | grep "nginx" | awk '{gsub("nginx/","",$3); print $3}'` = {{ nginx.version }} && echo True
  register: result
  ignore_errors: yes

- name: Install dependancies
  action: apt pkg={{ item }} state=present
  sudo: yes
  when: result|failed
  with_items:
    - libpcre3
    - libpcre3-dev
    - libgd2-xpm-dev
    - libgeoip-dev
    - libpam0g-dev
    - libcurl4-gnutls-dev
    - zlibc
    - zlib1g
    - zlib1g-dev

- name: Download Source
  get_url: url=http://nginx.org/download/nginx-{{ nginx.version }}.tar.gz dest=/opt/
  sudo: yes
  when: result|failed

- name: Unzip Nginx Tar
  unarchive: src=nginx-{{ nginx.version }}.tar.gz dest=/opt copy=no group=deploy owner=deploy
  sudo: yes
  when: result|failed

- name: Take Ownership of Folder
  file: path=/opt/nginx-{{ nginx.version }} owner=deploy group=deploy recurse=yes state=directory
  sudo: yes
  when: result|failed

- name: Download Third Party modules
  get_url: url=http://www.dropbox.com/s/e3n2lin6dvqlaos/modules.tar.gz dest=/opt/nginx-{{ nginx.version }}
  when: result|failed

- name: Unzip Modules
  unarchive: src=modules.tar.gz dest=/opt/nginx-{{ nginx.version }} copy=no group=deploy owner=deploy
  when: result|failed

- include: passenger.yml
  when: nginx.passenger == "true"

- name: Change Directory & Configure
  shell: ./configure --user=www-data --group=www-data --prefix=/opt/nginx --sbin-path=/usr/sbin --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --lock-path=/var/run/nginx.lock --pid-path=/var/run/nginx.pid --with-http_geoip_module --with-http_gzip_static_module --with-http_realip_module --with-http_stub_status_module --with-http_ssl_module --with-http_sub_module --with-http_xslt_module --with-ipv6 --with-sha1=/usr/include/openssl --with-md5=/usr/include/openssl --with-mail --with-mail_ssl_module --add-module=modules/ngx_http_auth_pam_module-1.2 --add-module=modules/echo-nginx-module-0.51 --add-module=modules/nginx-upstream-fair --add-module=modules/nginx-dav-ext-module-0.0.3 chdir=/opt/nginx-{{ nginx.version }}
  when: result|failed
  when: nginx.passenger == "false"

- name: Make
  shell: /usr/bin/make chdir=/opt/nginx-{{ nginx.version }}
  sudo: yes
  when: result|failed

- name: Make Install
  shell: /usr/bin/make install chdir=/opt/nginx-{{ nginx.version }}/
  sudo: yes
  when: result|failed

- name: copy init.d configuration file
  copy: src=nginx_upstart.conf dest=/etc/init/nginx.conf
  sudo: yes
  when: result|failed

- name: Create conf.d Directory
  file: path=/etc/nginx/conf.d state=directory owner=root group=root
  sudo: yes
  when: result|failed

- name: Create Sites Enabled Directory
  file: path=/etc/nginx/sites-enabled state=directory owner=root group=root
  sudo: yes
  when: result|failed

- name: Create SSL directory
  file: path=/etc/nginx/ssl/ state=directory owner=root group=root
  sudo: yes
  when: result|failed

- include: custom.yml
  when: custom == "true"

- include: ssl.yml
  when: ssl == "true"